### ISSUE TITLE
Transfer ownership to @lanej

### ISSUE THREAD

**Issue by lanej** [lanej/hmac#12]
There appears to be some active interesting in maintaining this and the current implementation is falling behind in support modern dependency versions.

@engineyard, please transfer this to me or let's at least discuss a cooperative maintenance agreement.

**Comment by mushyy** [comment]
Hi @lanej 

Opening a discussion internally.

**Comment by dvalfre** [comment]
@lanej Engine Yard is happy to transfer the ownership over so to ensure the gem continues to be maintained.  Let us know if there is any particularity from your side that has to be observed or otherwise I'll trigger GitHub's process.

**Comment by lanej** [comment]
@dvalfre let's do it! thanks for responding!

**Comment by dvalfre** [comment]
@lanej - GH is not allowing the transfer.  Getting this message from GH:

```
lanej/hmac already exists and You can only transfer a repository from an organization to yourself at this time
```
which seems related to 

```
The target account must not have a repository with the same name, or a fork in the same network.
```

from [GH's docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository).

**Comment by lanej** [comment]
Ah my bad, I'll delete my fork.

**Comment by lanej** [comment]
Ok @dvalfre one more time please.

**Comment by dvalfre** [comment]
@lanej transfer is done.  All well and good from your side?

**Comment by lanej** [comment]
YES! thanks @dvalfre
