### ISSUE TITLE
Query params are not signed which allows MITM

### ISSUE THREAD

**Issue by cmlad** [lanej/hmac#8]
Why are query params specifically excluded from the HMAC signature?

`adapter.rb` only ask for the path (`i.e. '/blogs/1'`):
https://github.com/engineyard/hmac/blob/8a2894545bf57f854409975ea695ee9f5e95da0f/lib/ey-hmac/adapter.rb#L59

Rack adapter uses `request.path` which omits the query params:
https://github.com/engineyard/hmac/blob/8a2894545bf57f854409975ea695ee9f5e95da0f/lib/ey-hmac/adapter/rack.rb#L46

Not having query params part of the HMAC signature exposes them to modification by MITM.

The fact that Rails exposes a single `params` variable that unites query params and POST data, and gives query params priority, make this even worse. The receiver will not even realize he's using a MITM-d query param instead of the POST data in the same request.

**Comment by itstehkman** [comment]
@lanej is there any update on this?

**Comment by lanej** [comment]
IDK what the wisdom was at the time.  I was a child when I wrote this but I agree your complaint is valid.  It would be far more secure to include query parameters.

Worth nothing that while rails controller params will mix query and body data together, you can still access them individually so you shouldn't have been blocked from restricting your inputs.
