### ISSUE TITLE
Target signature should not be in error message

### ISSUE THREAD

**Issue by jborrey** [lanej/hmac#9]
If there is a signature mismatch, an error message is raised [which includes the target signature](https://github.com/engineyard/hmac/blob/8a2894545bf57f854409975ea695ee9f5e95da0f/lib/ey-hmac/adapter.rb#L132).

This means it could easily end up in a logging pipeline, returned to the caller, etc. Since it contains the target signature, an attacker can just trivially force the error with their payload of choice, and then replace their first signature with the returned one and make a valid call.

Obvious fix is just not to return any such data. Error message, when dealing with anything cryptographic, are best kept as blank as possible.

**Comment by lanej** [comment]
This is fair.
